name: Node CI

on: [push]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
